<h1 style="color:#1F4E79;">DCWP Consumer Complaints Analysis</h1>

<p style="font-size:16px; color:#555;">
<b>Data Cleaning & Preparation</b><br>
Python • Pandas • Data Analytics
</p>

<hr style="border:1px solid #D9EAF7;">

<h2 style="color:#2F75B5;">1. Project Overview</h2>

This project analyzes consumer complaint records published by the New York City Department of Consumer and Worker Protection (DCWP).

The dataset contains information about consumer complaints, businesses, complaint categories, intake channels, complaint results, referrals, locations, and other related details.

The purpose of this project is to clean and prepare the dataset for further exploratory data analysis (EDA). Data cleaning is an important step because real-world datasets may contain missing values, inconsistent entries, duplicate records, incorrect data types, and other data-quality issues.

### Objectives of Data Cleaning

The main objectives of the data-cleaning process are:

- Understand the structure and contents of the dataset.
- Identify missing values and highly incomplete columns.
- Clean and convert financial values into suitable numeric formats.
- Convert date columns into proper datetime format.
- Identify and handle inconsistent or placeholder values.
- Standardize categorical data where appropriate.
- Correct data types for identifier and code-related columns.
- Check for duplicate records.
- Validate the final cleaned dataset.
- Save the cleaned dataset for further analysis.

The cleaned dataset will be used for the Exploratory Data Analysis (EDA) phase of the project.

<h2 style="color:#2F75B5;">2. Importing Required Libraries</h2>

The following Python libraries are used in this project:

- **Pandas** – for data loading, manipulation, cleaning, and analysis.
- **NumPy** – for handling missing values and numerical operations.
- **Matplotlib** – for creating visualizations.
- **Seaborn** – for statistical visualizations.

These libraries provide the basic tools required for the data-cleaning and analysis process.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

<h2 style="color:#2F75B5;">3. Loading the Dataset</h2>

The raw consumer complaints dataset is stored as a CSV file in the project's `data/raw` folder.

The dataset is loaded into a Pandas DataFrame so that it can be inspected, cleaned, and prepared for further analysis.

The raw dataset is kept unchanged so that the original data remains available for reference and reproducibility.

In [3]:
df = pd.read_csv("../data/raw/DCWP_Consumer_Complaints_20260918.csv")
print("Dataset loaded successfully.")

Dataset loaded successfully.

<h2 style="color:#2F75B5;">4. Initial Dataset Inspection</h2>

Before performing any cleaning operations, the dataset is inspected to understand its structure, size, columns, data types, and sample records.

This initial inspection helps identify potential data-quality issues that need to be addressed during the cleaning process.

**Preview of the Dataset**

The first few records are displayed to understand the structure and content of the dataset.

In [4]:
df.head()

,Record ID,Intake Date,Intake Channel,311 SR Number,Business Category,Complaint Code,Business Unique ID,Business Name,Result Date,Result,Referred To,Contract Cancelled Amount,Refund Amount,Address Type,Building Nbr,Street1,Street2,Street3,Unit Type,Apt/Suite,City,State,Postcode,Borough,Community Board,Council District,BIN,BBL,NTA,Census Block (2010),Census Tract (2010),Latitude,Longitude
0,000001-2026-CMPL,01/01/2026,311,311-25776008,Garage & Parking Lot,Non-Delivery of Goods - N01,BA-1758638-2026,PLATINUM PLUS GARAGE,02/01/2026,Requested Information Not Provided,NaN,NaN,NaN,Complete Address,350,E 30TH ST,NaN,NaN,NaN,NaN,NEW YORK,NY,10016,Manhattan,106.0,4.0,1020634.0,1.009358e+09,MN20,3000.0,70.0,40.741635,-73.976219
1,000002-2026-CMPL,01/01/2026,311,311-25776542,Tow Truck Company,Lost/Stolen/Damaged Property,BA-1758639-2026,Legacy Towing,02/01/2026,Requested Information Not Provided,NaN,NaN,NaN,Complete Address,13101,39TH AVE,NaN,NaN,NaN,NaN,FLUSHING,NY,11354,Queens,407.0,20.0,4112199.0,4.049630e+09,QN22,2008.0,871.0,40.758836,-73.835231
2,000003-2026-CMPL,01/01/2026,311,311-25776844,Specialized Vending License - MFV,Advertising/Misleading - A02,BA-1758640-2026,The flavor of the new yorm,01/02/2026,Insufficient Info Received,NaN,NaN,NaN,Complete Address,134,W 43RD ST,NaN,NaN,NaN,NaN,NEW YORK,NY,10036,Manhattan,105.0,4.0,1087268.0,1.009950e+09,MN17,1005.0,119.0,40.755920,-73.984606
3,000004-2026-CMPL,01/01/2026,Online,NaN,Garage & Parking Lot,Other - Z01,BA-1287019-2022,"LAUREATE GARAGE, LLC",02/15/2026,Requested Information Not Provided,NaN,NaN,NaN,Complete Address,2148,BROADWAY,NaN,NaN,NaN,NaN,NEW YORK,NY,10023,Manhattan,107.0,6.0,1088786.0,1.011678e+09,MN12,5002.0,163.0,40.781385,-73.981177
4,000005-2026-CMPL,01/01/2026,Online,NaN,Garage & Parking Lot,Non-Delivery of Service - N02,BA-1758642-2026,LAUREATE GARAGE LLC,02/15/2026,Requested Information Not Provided,NaN,NaN,NaN,Complete Address,NaN,2148 Broadway,NaN,NaN,NaN,NaN,New York,NY,10023,Manhattan,107.0,6.0,1088786.0,1.011678e+09,MN12,5002.0,163.0,40.781385,-73.981177

**Dataset Dimensions**

The dataset contains the following number of rows and columns.

In [5]:
df.shape

(76527, 33)

In [6]:
df.columns.tolist()

['Record ID',
 'Intake Date',
 'Intake Channel',
 '311 SR Number',
 'Business Category',
 'Complaint Code',
 'Business Unique ID',
 'Business Name',
 'Result Date',
 'Result',
 'Referred To',
 'Contract Cancelled Amount',
 'Refund Amount',
 'Address Type',
 'Building Nbr',
 'Street1',
 'Street2',
 'Street3',
 'Unit Type',
 'Apt/Suite',
 'City',
 'State',
 'Postcode',
 'Borough',
 'Community Board',
 'Council District',
 'BIN',
 'BBL',
 'NTA',
 'Census Block (2010)',
 'Census Tract (2010)',
 'Latitude',
 'Longitude']

In [7]:
df.dtypes

Record ID                     object
Intake Date                   object
Intake Channel                object
311 SR Number                 object
Business Category             object
Complaint Code                object
Business Unique ID            object
Business Name                 object
Result Date                   object
Result                        object
Referred To                   object
Contract Cancelled Amount     object
Refund Amount                 object
Address Type                  object
Building Nbr                  object
Street1                       object
Street2                       object
Street3                       object
Unit Type                     object
Apt/Suite                     object
City                          object
State                         object
Postcode                      object
Borough                       object
Community Board              float64
Council District             float64
BIN                          float64
BBL                          float64
NTA                           object
Census Block (2010)          float64
Census Tract (2010)          float64
Latitude                     float64
Longitude                    float64
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76527 entries, 0 to 76526
Data columns (total 33 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Record ID                  76527 non-null  object
 1   Intake Date                76527 non-null  object
 2   Intake Channel             76527 non-null  object
 3   311 SR Number              53763 non-null  object
 4   Business Category          75129 non-null  object
 5   Complaint Code             65750 non-null  object
 6   Business Unique ID         74030 non-null  object
 7   Business Name              73154 non-null  object
 8   Result Date                76527 non-null  object
 9   Result                     76527 non-null  object
 10  Referred To                28002 non-null  object
 11  Contract Cancelled Amount  46 non-null     object
 12  Refund Amount              1509 non-null   object
 13  Address Type               72887 non-null  object
 14  Building Nbr               64041 non-null  object
 15  Street1                    72837 non-null  object
 16  Street2                    3167 non-null   object
 17  Street3                    141 non-null    object
 18  Unit Type                  3996 non-null   object
 19  Apt/Suite                  6733 non-null   object
 20  City                       70599 non-null  object
 21  State                      72806 non-null  object
 22  Postcode                   72780 non-null  object
 23  Borough                    66914 non-null  object
 24  Community Board            65935 non-null  float64
 25  Council District           65935 non-null  float64
 26  BIN                        61148 non-null  float64
 27  BBL                        61148 non-null  float64
 28  NTA                        63073 non-null  object
 29  Census Block (2010)        63073 non-null  float64
 30  Census Tract (2010)        65932 non-null  float64
 31  Latitude                   66400 non-null  float64
 32  Longitude                  66400 non-null  float64
dtypes: float64(8), object(25)
memory usage: 19.3+ MB

<h2 style="color:#2F75B5;">5. Missing Value Analysis</h2>

Missing values are common in real-world datasets. Before deciding how to handle them, the number and percentage of missing values in each column are examined.

This helps identify columns that are highly incomplete and determine whether the missing values should be removed, retained, or handled in another way.

In [9]:
missing_count = df.isnull().sum()

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_count,
    "Missing Percentage": missing_percentage
})

missing_summary = missing_summary.sort_values(
    by="Missing Percentage",
    ascending=False
)

missing_summary

                           Missing Values  Missing Percentage
Contract Cancelled Amount           76481           99.939890
Street3                             76386           99.815751
Refund Amount                       75018           98.028147
Street2                             73360           95.861591
Unit Type                           72531           94.778314
Apt/Suite                           69794           91.201798
Referred To                         48525           63.408993
311 SR Number                       22764           29.746364
BBL                                 15379           20.096175
BIN                                 15379           20.096175
Census Block (2010)                 13454           17.580723
NTA                                 13454           17.580723
Building Nbr                        12486           16.315810
Complaint Code                      10777           14.082611
Census Tract (2010)                 10595           13.844787
Council District                    10592           13.840867
Community Board                     10592           13.840867
Latitude                            10127           13.233238
Longitude                           10127           13.233238
Borough                              9613           12.561580
City                                 5928            7.746286
Postcode                             3747            4.896311
State                                3721            4.862336
Street1                              3690            4.821828
Address Type                         3640            4.756491
Business Name                        3373            4.407595
Business Unique ID                   2497            3.262901
Business Category                    1398            1.826806
Intake Date                             0            0.000000
Result                                  0            0.000000
Result Date                             0            0.000000
Intake Channel                          0            0.000000
Record ID                               0            0.000000

<h3 style="color:#5B9BD5;">Removing Highly Sparse Columns</h3>

The following address-detail columns contained more than 90% missing values and were removed because they provided limited information for the analysis:

- Street2
- Street3
- Unit Type
- Apt/Suite

Financial columns with high missing values were retained because their available values may provide useful information.

**Handling Highly Sparse Columns**

Columns with extremely high proportions of missing values were removed when they provided limited analytical value for the project.

In [10]:
df.drop(
    columns=["Street2", "Street3", "Unit Type", "Apt/Suite"],
    inplace=True
)

print(df.shape)

(76527, 29)

<h2 style="color:#2F75B5;">6. Cleaning Financial Columns</h2>

The `Contract Cancelled Amount` and `Refund Amount` columns contain monetary values.

The values contain currency symbols and commas, which need to be removed before converting the columns into numeric format.

Missing values are retained because a missing amount does not necessarily mean that the amount was zero.

In [11]:
df[["Contract Cancelled Amount", "Refund Amount"]].describe()

       Contract Cancelled Amount Refund Amount
count                         46          1509
unique                        44           607
top                       $3,000       $10,000
freq                           2            82

In [12]:
df[["Contract Cancelled Amount", "Refund Amount"]].head(20)

   Contract Cancelled Amount Refund Amount
0                        NaN           NaN
1                        NaN           NaN
2                        NaN           NaN
3                        NaN           NaN
4                        NaN           NaN
5                        NaN           NaN
6                        NaN           NaN
7                        NaN           NaN
8                        NaN           NaN
9                        NaN           NaN
10                       NaN           NaN
11                       NaN           NaN
12                       NaN           NaN
13                       NaN           NaN
14                       NaN           NaN
15                       NaN           NaN
16                       NaN           NaN
17                       NaN           NaN
18                       NaN           NaN
19                       NaN          $110

In [13]:
df["Contract Cancelled Amount"] = (
    df["Contract Cancelled Amount"]
    .astype("string")
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["Refund Amount"] = (
    df["Refund Amount"]
    .astype("string")
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
)

df["Contract Cancelled Amount"] = pd.to_numeric(
    df["Contract Cancelled Amount"],
    errors="coerce"
)

df["Refund Amount"] = pd.to_numeric(
    df["Refund Amount"],
    errors="coerce"
)

In [14]:
df[["Contract Cancelled Amount", "Refund Amount"]].dtypes

Contract Cancelled Amount    Int64
Refund Amount                Int64
dtype: object

In [15]:
df[["Contract Cancelled Amount", "Refund Amount"]].head(20)

    Contract Cancelled Amount  Refund Amount
0                        <NA>           <NA>
1                        <NA>           <NA>
2                        <NA>           <NA>
3                        <NA>           <NA>
4                        <NA>           <NA>
5                        <NA>           <NA>
6                        <NA>           <NA>
7                        <NA>           <NA>
8                        <NA>           <NA>
9                        <NA>           <NA>
10                       <NA>           <NA>
11                       <NA>           <NA>
12                       <NA>           <NA>
13                       <NA>           <NA>
14                       <NA>           <NA>
15                       <NA>           <NA>
16                       <NA>           <NA>
17                       <NA>           <NA>
18                       <NA>           <NA>
19                       <NA>            110

<h2 style="color:#2F75B5;">7. Cleaning Date Columns</h2>

The `Intake Date` and `Result Date` columns contain dates in text format.

**Date Format Standardization**

The `Intake Date` and `Result Date` columns are converted to datetime format to enable accurate date-based analysis.

In [16]:
df["Intake Date"] = pd.to_datetime(
    df["Intake Date"],
    format="%m/%d/%Y",
    errors="coerce"
)

df["Result Date"] = pd.to_datetime(
    df["Result Date"],
    format="%m/%d/%Y",
    errors="coerce"
)

In [17]:
df[["Intake Date", "Result Date"]].dtypes

Intake Date    datetime64[ns]
Result Date    datetime64[ns]
dtype: object

<h3 style="color:#5B9BD5;">Checking Date Consistency</h3>

The `Result Date` should normally occur on or after the `Intake Date`.

Records where the `Result Date` occurs before the `Intake Date` are checked for possible date inconsistencies.

In [18]:
invalid_dates = df[df["Result Date"] < df["Intake Date"]]

invalid_dates[["Record ID", "Intake Date", "Result Date", "Result"]]

              Record ID Intake Date Result Date                Result
28866  042731-2024-CMPL  2024-07-27  2024-07-26              Referred
63892   10355-2023-CMPL  2023-07-27  2023-07-20  Advised to Sue - ATS

In [19]:
df.loc[df["Result Date"] < df["Intake Date"], "Result Date"] = pd.NaT

The two records with inconsistent date order were identified. Since the correct dates could not be determined from the available data, the inconsistent `Result Date` values were set to missing rather than assigning assumed dates.

<h2 style="color:#2F75B5;">8. Cleaning Categorical Columns</h2>

<h3 style="color:#5B9BD5;">Categorical Data Inspection</h3>

The categorical columns were inspected to identify inconsistent formatting, placeholder values, and unusual entries before applying appropriate cleaning operations.

In [20]:
df["City"].value_counts(dropna=False)

City
BROOKLYN            18322
NEW YORK            17890
BRONX                9504
NaN                  5928
STATEN ISLAND        1967
                    ...
DURYEA                  1
COLORADO SPRINGS        1
Elche                   1
Louisville              1
Fordham Heights         1
Name: count, Length: 1382, dtype: int64

In [21]:
df["Intake Channel"].value_counts(dropna=False)

Intake Channel
311                 53771
Online              17524
Email/Fax            2634
Hardcopy             2073
Cloned                264
Phone                 245
Walk-In                11
External Affairs        5
Name: count, dtype: int64

In [22]:








df["State"].value_counts(dropna=False)

State
NY             70657
NaN             3721
NJ               384
CA               297
Outside USA      135
FL               133
TX               115
PA               112
WA                70
CO                69
MN                68
MA                67
IL                66
OH                57
VA                56
GA                53
SC                51
CT                46
DE                40
MI                39
UT                39
NC                37
NV                26
MO                23
TN                21
MD                16
IN                14
SD                13
AZ                13
WI                12
AR                11
OR                10
DC                 9
AL                 8
LA                 7
KS                 6
KY                 6
IA                 5
NH                 3
OK                 3
NE                 2
WV                 1
ID                 1
ME                 1
MS                 1
WY                 1
ND                 1
NM                 1
Name: count, dtype: int64

In [23]:
df["Borough"].value_counts(dropna=False)

Borough
Manhattan        19712
Brooklyn         19305
Queens           15394
Bronx             9954
NaN               9613
Staten Island     1983
Outside NYC        566
Name: count, dtype: int64

In [24]:
df["Result"].value_counts(dropna=False)

Result
Referred                                              25633
Requested Information Not Provided                    23658
Complaint Review Complete                             11060
Insufficient Info Received                             4885
No Jurisdiction                                        1919
Information Provided                                   1412
Advised to Sue - ATS                                   1302
Duplicate Complaint - DUP                              1051
Resolved and Consumer Satisfied - SPF                  1007
No Business Response - NVR                              996
Cash Amount - AMT                                       808
No Consumer Response - NCR                              696
Credit Card Refund and/or Contract Cancelled - CRC      399
No Satisfactory Agreement - NSA                         335
Business Reported                                       243
Referred to Outside - RTO                               217
Inspection Requested                                    180
Consumer Took Action - CTA                              119
Bill Reduced - BLR                                      117
Store Credit - SCR                                      104
Wrong Business and Null and Void - NUL                   73
Goods Repaired - GRS                                     73
Unable to Locate Business- ULV                           51
Goods Received - GDR                                     44
Goods Exchanged - GEX                                    34
Consumer Withdrew Complaint - CWC                        33
Complaint Invalid - CIN                                  33
Referred to Hearing - RTH                                27
Technical Problem                                         5
Referred to Manufacturer - RMF                            4
Agency Collected Judgement - ACJ                          4
Provider Feedback Received                                2
Unable to Locate Customer - ULC                           2
Out of Business - OOB                                     1
Name: count, dtype: int64

In [25]:
df["Address Type"].value_counts(dropna=False)

Address Type
Complete Address               69639
NaN                             3640
Cross Street (Intersection)     2859
Place (Landmark)                 239
Block                            142
P.O. Box                           8
Name: count, dtype: int64

In [26]:
df["Business Category"].value_counts(dropna=False)

Business Category
Other                                                       11105
Misc Non-Food Retail                                         6077
Tow Truck Company                                            5587
Restaurant                                                   3835
Supermarket                                                  3460
                                                            ...
Collection Business Category                                    1
Gaming Cafe                                                     1
Amusement Device Portable                                       1
Motion Picture Operator - 123                                   1
Games of Chance - Raffle with Net Proceeds Under $30,000        1
Name: count, Length: 116, dtype: int64

In [27]:
df["Referred To"].value_counts(dropna=False)

Referred To
NaN                             48525
Other                            7484
NYC Department of Sanitation     3820
-                                2442
NYC Police Department            1833
                                ...
INS-000895326                       1
INS-000886316                       1
INS-000890975                       1
INS-000886716                       1
INS-000974629                       1
Name: count, Length: 386, dtype: int64

<h3 style="color:#5B9BD5;">Handling Placeholder Values</h3>

Some categorical fields contain placeholder values such as `-`, `Unknown`, `No name`, `none`, and `0`.

These values do not represent meaningful information, so they are treated as missing values where appropriate.

In [28]:
(df == "-").sum().sort_values(ascending=False)

Referred To                  2442
Business Name                   8
Record ID                       0
City                            0
Latitude                        0
Census Tract (2010)             0
Census Block (2010)             0
NTA                             0
BBL                             0
BIN                             0
Council District                0
Community Board                 0
Borough                         0
Postcode                        0
State                           0
Building Nbr                    0
Street1                         0
Intake Date                     0
Address Type                    0
Refund Amount                   0
Contract Cancelled Amount       0
Result                          0
Result Date                     0
Business Unique ID              0
Complaint Code                  0
Business Category               0
311 SR Number                   0
Intake Channel                  0
Longitude                       0
dtype: Int64

In [29]:
df["Referred To"] = df["Referred To"].replace("-", "Not Specified")

df["Business Name"] = df["Business Name"].replace(
    ["-", "Unknown", "unknown", "No name", "no name", "none", "0"],
    np.nan
)

df["311 SR Number"] = df["311 SR Number"].replace("0", np.nan)

df["Building Nbr"] = df["Building Nbr"].replace("0", np.nan)

df["Street1"] = df["Street1"].replace("0", np.nan)

df["Postcode"] = df["Postcode"].replace("0", np.nan)

In [30]:
df[df["Business Name"] == "-"][["Business Name", "Business Category", "Result", "Referred To"]]

Empty DataFrame
Columns: [Business Name, Business Category, Result, Referred To]
Index: []

<h3 style="color:#5B9BD5;">Standardizing City Names</h3>

City names were standardized to uppercase to maintain consistent formatting across the dataset.

In [31]:
df["City"] = df["City"].str.upper()

In [32]:
df[["City", "Business Name", "Referred To"]].head()

       City               Business Name Referred To
0  NEW YORK        PLATINUM PLUS GARAGE         NaN
1  FLUSHING               Legacy Towing         NaN
2  NEW YORK  The flavor of the new yorm         NaN
3  NEW YORK        LAUREATE GARAGE, LLC         NaN
4  NEW YORK         LAUREATE GARAGE LLC         NaN

In [33]:
id_columns = [
    "Record ID",
    "311 SR Number",
    "Business Unique ID",
    "Building Nbr",
    "Postcode",
    "Community Board",
    "Council District",
    "BIN",
    "BBL",
    "Census Block (2010)",
    "Census Tract (2010)"
]

df[id_columns].dtypes

Record ID               object
311 SR Number           object
Business Unique ID      object
Building Nbr            object
Postcode                object
Community Board        float64
Council District       float64
BIN                    float64
BBL                    float64
Census Block (2010)    float64
Census Tract (2010)    float64
dtype: object

<h2 style="color:#2F75B5;">9. Correcting Data Types</h2>
Some identifier and code-related columns are stored as numeric values.

These columns are identifiers rather than measurements, so they are converted to string format to preserve their values correctly.

In [34]:
id_numeric_columns = [
    "Community Board",
    "Council District",
    "BIN",
    "BBL",
    "Census Block (2010)",
    "Census Tract (2010)"
]

for column in id_numeric_columns:
    df[column] = df[column].astype("Int64").astype("string")

In [35]:
#Checking
df[id_numeric_columns].dtypes

Community Board        string[python]
Council District       string[python]
BIN                    string[python]
BBL                    string[python]
Census Block (2010)    string[python]
Census Tract (2010)    string[python]
dtype: object

<h2 style="color:#2F75B5;">10. Checking Duplicate Records</h2>

Duplicate records can affect the accuracy of analysis, so the dataset is checked for exact duplicate rows.

Records with the same `Record ID` are also examined separately because the same identifier may appear in multiple rows with different information.

In [36]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [37]:
print("Duplicate Record IDs:", df["Record ID"].duplicated().sum())

Duplicate Record IDs: 137

In [38]:
duplicate_ids = df[df["Record ID"].duplicated(keep=False)]

print("Rows with duplicate Record IDs:", len(duplicate_ids))

Rows with duplicate Record IDs: 271

No exact duplicate rows were found in the dataset.

Some `Record ID` values occur more than once, but these records contain different information in other columns. Therefore, they were retained rather than removed.

In [39]:
duplicate_ids[
    ["Record ID", "Intake Date", "Business Name", "Complaint Code", "Result"]
].sort_values("Record ID").head(30)

,Record ID,Intake Date,Business Name,Complaint Code,Result
1109,001275-2026-CMPL,2026-01-18,Paypal Inc,Exchange/Refund/Return,Referred to Outside - RTO
1110,001275-2026-CMPL,2026-01-18,"PayPal, Inc.",Exchange/Refund/Return,Referred to Outside - RTO
2664,003279-2026-CMPL,2026-02-14,Shop Fair,Overcharge,Requested Information Not Provided
69713,003279-2026-CMPL,2026-02-14,A & J MEAT MARKET INC,Overcharge; Cashless Business,Complaint Review Complete
71983,004608-2026-CMPL,2026-03-04,The Clutterless Company,Overcharge,Complaint Review Complete
66895,004608-2026-CMPL,2026-03-04,The Clutterless Company,NaN,Requested Information Not Provided
76027,006266-2026-CMPL,2026-03-24,LifeX Research Corporation,Misrepresentation - M01,Referred
70395,006266-2026-CMPL,2026-03-24,LifeX Research Corporation,Misrepresentation - M01,Complaint Review Complete
75826,006935-2026-CMPL,2026-04-01,26 MOTORS COMMERCIAL LLC,Contract or Billing Dispute,Referred
69974,006935-2026-CMPL,2026-04-01,26 MOTORS,Contract or Billing Dispute,Requested Information Not Provided
69580,006935-2026-CMPL,2026-04-01,26 MOTORS COMMERCIAL LLC,Contract or Billing Dispute,Requested Information Not Provided
76486,006935-2026-CMPL,2026-04-01,26 MOTORS,Contract or Billing Dispute,Referred
76301,008695-2026-CMPL,2026-04-21,LA VICTORIA FOUNDATION,Non-Delivery of Goods - N01,Requested Information Not Provided
67261,008695-2026-CMPL,2026-04-21,LA VICTORIA FOUNDATION,Non-Delivery of Goods - N01,Complaint Review Complete
71577,008711-2026-CMPL,2026-04-21,7F’S CAFE INC.,Unlicensed,Inspection Requested
73631,008711-2026-CMPL,2026-04-21,7F’S CAFE INC.,Unlicensed,Inspection Requested
4807,014685-2023-CMPL,2023-08-15,東粵海鮮酒家 Dong Yue seafood restaurant,NaN,Requested Information Not Provided
4806,014685-2023-CMPL,2023-08-15,Dong Yue Seafood Restaurant,NaN,Requested Information Not Provided
5339,015348-2023-CMPL,2023-08-08,GAMESTOP INC.,Exchange/Refund/Return,Resolved and Consumer Satisfied - SPF
5338,015348-2023-CMPL,2023-08-08,Gamestop Corp.,Exchange/Refund/Return,Resolved and Consumer Satisfied - SPF
5587,015635-2023-CMPL,2023-08-12,Chimichurri Charcoal Kitchen Corp.,NaN,Referred
5586,015635-2023-CMPL,2023-08-12,Chimichurri Charcoal Chicken,NaN,Referred
9656,020369-2023-CMPL,2023-10-12,"SCALISE, FIORE",NaN,Referred to Hearing - RTH
9655,020369-2023-CMPL,2023-10-12,fiore general contracting,NaN,Referred to Hearing - RTH
10826,021690-2023-CMPL,2023-10-27,NaN,NaN,Complaint Review Complete
10827,021690-2023-CMPL,2023-10-27,renewal by anderson of long island,NaN,Complaint Review Complete
11706,022690-2023-CMPL,2023-11-10,VICTORY MITSUBISHI,Contract Terms Misleading or Not Disclosed,Advised to Sue - ATS
11705,022690-2023-CMPL,2023-11-10,SPARTAN AUTO GROUP LLC,Contract Terms Misleading or Not Disclosed,Advised to Sue - ATS
13223,024350-2023-CMPL,2025-02-18,New Leaf Home Improvement LLC,NaN,Duplicate Complaint - DUP
13222,024350-2023-CMPL,2025-02-18,H G RENOVATION CORP.,NaN,Duplicate Complaint - DUP

Repeated `Record ID` values were retained because the corresponding records were not exact duplicates and contained differences in fields such as Business Name, Complaint Code, or Result.

<h2 style="color:#2F75B5;">11. Final Validation</h2>

The cleaned dataset was validated to confirm that the expected number of rows and columns were retained and that no exact duplicate rows remained.

In [40]:
print("Final shape:", df.shape)
print("Exact duplicate rows:", df.duplicated().sum())

Final shape: (76527, 29)
Exact duplicate rows: 0

<h2 style="color:#2F75B5;">12. Saving the Cleaned Dataset</h2>

After completing the cleaning and validation steps, the cleaned dataset is saved as a separate CSV file.

The original raw dataset is kept unchanged, while the cleaned version is stored in the `data/cleaned` folder for use in the next stage of the project.

In [41]:
df.to_csv("../data/cleaned/DCWP_Consumer_Complaints_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Cleaned dataset saved successfully!
Rows: 76527
Columns: 29

<h2 style="color:#2F75B5;">Data Cleaning Summary</h2>

### Dataset Overview

- **Original dataset:** 76,527 rows × 33 columns
- **Final cleaned dataset:** 76,527 rows × 29 columns
- **Exact duplicate rows:** 0

### Cleaning Performed

**1. Highly Sparse Columns**

Removed `Street2`, `Street3`, `Unit Type`, and `Apt/Suite` because they contained extremely high proportions of missing values and provided limited analytical value.

**2. Financial Columns**

Cleaned `Contract Cancelled Amount` and `Refund Amount` by removing currency symbols and commas and converting them to numeric format. Missing values were retained rather than automatically treated as zero.

**3. Date Columns**

Converted `Intake Date` and `Result Date` to datetime format. Two records contained a Result Date earlier than the Intake Date; these inconsistent Result Date values were set to missing because the correct dates could not be determined.

**4. Categorical Columns**

- Standardized city names to uppercase.
- Replaced inappropriate placeholder values such as `Unknown`, `No name`, `none`, and `0` with missing values where appropriate.
- Replaced `-` in `Referred To` with `Not Specified`.

**5. Data Types**

Converted identifier and code-related columns to string format to preserve their identifier nature.

**6. Duplicate Records**

No exact duplicate rows were found. Repeated `Record ID` values were retained because the corresponding records contained differences in other fields.

### Final Validation

- **Rows:** 76,527
- **Columns:** 29
- **Exact duplicate rows:** 0
- **Date fields:** Converted successfully
- **Financial fields:** Converted to numeric format
- **Identifier fields:** Preserved as strings

The cleaned dataset was saved as:

`DCWP_Consumer_Complaints_Cleaned.csv`